// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


const ARGS_MAP = { '':'{"start_mouse_listener":[],"greet":["name"]}' }
export type Router = { '': { greet: (name: string) => Promise<string>, 
start_mouse_listener: () => Promise<null> } };


export type { InferCommandOutput }
export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
